## Telegram Bot Settings
token: 
botid: 
chatid: 
message: BDO disconnected

## Program Settings
stayalive: false
process: BlackDesert64.exe
timebetweenchecksins: 5
shutdownondc: false

## Currently disabled
killondc: true

