## Get updates here: https://github.com/tzerk/BDO-Watchdog/releases/
## Telegram Bot Settings
token: 
botid: 
chatid: 
timestamp: true
message: BDO disconnected

## Program Settings
stayalive: false
process: BlackDesert64.exe
timebetweenchecksins: 60
faillimit: 2

# These settings require the .exe to be run with admin rights! 
killondc: true
shutdownondc: false
killcoherentui: false
log: true

# Set the process priority. Allowed values are: idle, below normal, normal, above normal, high priority, realtime
# Also requires admin rights!
processpriority: normal