## Telegram Bot Settings
token: 
botid: 
chatid: 
message: BDO disconnected

## Program Settings
stayalive: false
process: BlackDesert64.exe
timebetweenchecksins: 60

# These settings require the .exe to be run with admin rights! 
killondc: false
shutdownondc: false
killcoherentui: false

